version: '3.4'
services:
    api:
        build:
            context: .
            target: dev
        volumes: 
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports: 
            - 3000:3000
            - 9229:9229
        command: npm run start:dev
